### ISSUE TITLE
Python 3.7 is in use and end-of-support

### ISSUE THREAD

**Issue by kilianhuempfer** [lacework-alliances/aws-org-cf-lacework#4]
templates/lacework-aws-cfg-manage.template.yml
In main branch we use Runtime: python3.7 which is not longer supported by AWS. 

"We are ending support for Python 3.7 in AWS Lambda. This follows Python 3.7 End-Of-Life (EOL) reached on June 27, 2023 [1].

As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting November 27, 2023, Lambda will no longer apply security patches and other updates to the Python 3.7 runtime used by Lambda functions, and functions using Python 3.7 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Python 3.7 runtime. Starting January 25, 2024, you will no longer be able to update existing functions using the Python 3.7 runtime.

We recommend that you upgrade your existing Python 3.7 functions to Python 3.11 before November 27, 2023."

**Comment by jefferyfry** [comment]
Python version has been updated to 3.9.
